# Generated by Django 5.2.1 on 2025-05-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="manager",
            name="password",
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
