# Generated by Django 5.2.1 on 2025-05-16 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0002_manager_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manager",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="managers",
                to="expense.owner",
            ),
        ),
    ]
