# Generated by Django 5.2.1 on 2025-05-16 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0003_alter_manager_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sites",
                to="expense.owner",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="site",
            name="assigned_manager",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sites",
                to="expense.manager",
            ),
        ),
    ]
