# Generated by Django 5.2.1 on 2025-05-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0004_site_owner_alter_site_assigned_manager"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="site",
            name="assigned_manager",
        ),
        migrations.AddField(
            model_name="site",
            name="assigned_managers",
            field=models.ManyToManyField(
                blank=True, related_name="sites", to="expense.manager"
            ),
        ),
    ]
