# Generated by Django 5.2.1 on 2025-05-16 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0005_remove_site_assigned_manager_site_assigned_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteimage",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="expense.site",
            ),
        ),
        migrations.CreateModel(
            name="SiteExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("material_name", models.CharField(max_length=100)),
                ("quantity", models.PositiveIntegerField()),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(auto_now_add=True)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="expense.site",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SiteProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completion_percentage", models.PositiveIntegerField(default=0)),
                (
                    "site",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="expense.site",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="MaterialExpense",
        ),
    ]
