# Generated by Django 5.2.1 on 2025-05-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expense", "0006_alter_siteimage_site_siteexpense_siteprogress_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteexpense",
            name="completion_percentage",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="SiteProgress",
        ),
    ]
